### ISSUE TITLE
Modoru app title needs to be reset every time

### ISSUE THREAD

**Issue by Invictaz** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#1] opened 2022-09-06 23:26 UTC
The Modoru with Japanese sign behind it needs the "restore app title" and if you do it, it adds garbage signs to the app title again after you exit. If you press the "restore app title" again it temporarily fixes it.

**Comment by BlackSheepBoy69** [comment] 2022-09-09 03:15
It adds it again when you exit? Like if you exit the app and come back it adds the junk or is it just when you refresh? I would have thought refresh app title would fix it permanently until you refresh cache

**Comment by BlackSheepBoy69** [comment] 2022-09-10 05:26
Someone messaged me about a similar issue with a different game I don't have the vpk for. I got Modoru and couldn't reproduce the issue, do you have a copy of the exact vpk you used?

**Comment by Invictaz** [comment] 2022-09-17 13:46
How to extract a vpk from something that is installed?

**Comment by BlackSheepBoy69** [comment] 2022-09-17 15:06
I think the app ID of modoru is MODORU000, so if you don't have the vpk, then if you could send me just this file: ux0:app/MODORU000/sce_sys/param.sfo
which is the file HEXFlow scans to determine the name of an app (I think this is where the issue comes from) I can use it for bugtesting to fix this. If I can't get it fixed I'll at least try and make renames stick so they won't reset again after you exit.

**Comment by BlackSheepBoy69** [comment] 2023-03-25 07:40
Should be fixed in the latest version v1.1 👍👍👍

**Closed by BlackSheepBoy69** 2023-03-25 07:40 UTC
